### PR TITLE
Validation and setup script fixes

### LINKED ISSUE #56: Add waveform-* containers to emap setup script, do not run waveform-generator in production
This will include refactoring (just restructure directory?) to make clear that waveform-generator is for system testing only, and to make sure it only runs when explicitly asked for.
Validation testing may use a test file with real data in it, and/or data from waveform-generator.

### PR DESCRIPTION
**Pull request by jeremyestein**
Fixes #56 , waveform turned off in production (but optional in validation)

### CODE REVIEW

File: hl7-reader/src/main/java/uk/ac/ucl/rits/inform/datasources/ids/IdsOperations.java [hunk 1]
```diff
@@ -156,22 +156,23 @@ private boolean getIdsIsEmpty() {
...
             return null;
         }
         logger.info("Querying IDS for first unid after {}, this can take a while", fromDateTime);
         try (Session idsSession = idsFactory.openSession()) {
+            idsSession.setDefaultReadOnly(true);
+            // Including `unid` anywhere in this query seems to make it do an index scan on the unid (PK) column
+            // and thus make it very slow.
             List<IdsMaster> msg = idsSession.createQuery(
-                            "select i from IdsMaster i where i.unid >= :fromUnid and i.persistdatetime >= :fromDatetime order by i.unid",
+                            "select i from IdsMaster i where i.persistdatetime >= :fromDatetime order by i.persistdatetime",
```
Comment (stefpiatek) [inline hl7-reader/src/main/java/uk/ac/ucl/rits/inform/datasources/ids/IdsOperations.java:173]: I had a feeling like when we didn't specify this, that we wouldn't get them ordered by unid in production. Might be worth doing a test of this against the IDS

Comment (jeremyestein) [reply hl7-reader/src/main/java/uk/ac/ucl/rits/inform/datasources/ids/IdsOperations.java:173]: Ah, good point. If I've got this query right, it should be doing the check:
```
select * from (
	select
	    ids.unid,
	    ids.persistdatetime,
	    row_number() over (order by unid) as by_unid,
	    row_number() over (order by persistdatetime) as by_dt
	from public.tbl_ids_master ids
) x
where
x.by_unid != x.by_dt
;
```

So far, the only ones that fail the test occur between 1 and 2 am on the last Sunday of each October 🙄 (at least as far as 2022)

Might suggest that the `persistdatetime` is not in fact timezone aware, as it claims to be :(

I *think* this doesn't make any difference in the case where we use a date that is not in this ambiguous window. This is already a bug if hl7-reader should record progress that happens to fall in this window.

I will have a think about what's best here...

Comment (jeremyestein) [reply hl7-reader/src/main/java/uk/ac/ucl/rits/inform/datasources/ids/IdsOperations.java:173]: TLDR:
- The IDS timestamp field is broken and we have been imperfectly working around it; this change makes that workaround worse
- In practice it likely only affects validation runs, not production
- It only applies if requesting a start/end date that occurs in the ambiguous date zone between 1am and 2am at the end of October (that I sometimes refer to as "programmer's halloween" ;)
- It doesn't affect order of message delivery in any case
- It could be worked around with a little manual binary searching, but probably not worth the effort
- the advantage of the new way is that I don't have to wait an hour every time I do a validation run!

Details:
Note that this doesn't affect the order in which we process the messages, it just affects the starting/ending unid when a date bound has been requested (true only in validation rather than production I believe?). The current unid is then incremented in the expected way.

However, it has I think a ~50% chance of missing up to an hour of messages if and only if the given date bound occurs between 1am and 2am on this day of the year.

In this diagram the arrowed line represents a series of messages with monotonically increasing unids, where there is a jump back an hour because of the local datetime incorrectly being used.
image

Imagine that the requested bound is b1, then using my query it will chose message m1 because it's slightly nearer in time to b1, when it should have chosen m2 (which has a lower unid).
If the bound is b2, then it will correctly chose m3, because the message that occurred in BST happened to be nearer to b2 in local time.

The old query gives the correct unid for times b1 and b2, but would fail for the short time that sits in between the last message before 2am and 2am itself. In that case it would wrongly pick m4 instead of m5.

When the bug occurs, it just means that the unid is unstable with respect to small changes in the input date. However, given that the input date is inherently ambiguous due to the IDS' use of local time, it's not clear what the user would be hoping for anyway.

You could fix it better by using the old query, but first doing a binary search to search for a better `:fromUnid ` timestamp (targetting the timestamp at least one hour before what the user actually asked for to avoid the ambiguity). This would at least give it stable (but still wrong) behaviour.

**Review by skeating — APPROVED** [review]

File: hl7-reader/src/main/java/uk/ac/ucl/rits/inform/datasources/ids/IdsOperations.java (hunk 1 above)
Comment (jeremyestein) [reply hl7-reader/src/main/java/uk/ac/ucl/rits/inform/datasources/ids/IdsOperations.java:173]: @stefpiatek What do you want me to do about this bit?

Comment (stefpiatek) [reply hl7-reader/src/main/java/uk/ac/ucl/rits/inform/datasources/ids/IdsOperations.java:173]: fix it in the easiest way possible, its only for validation so we don't care much about it if we lose an hour of data

Comment (jeremyestein) [reply hl7-reader/src/main/java/uk/ac/ucl/rits/inform/datasources/ids/IdsOperations.java:173]: As far as I can tell, the easiest thing to do that makes validation faster is to leave it as it is.
